# use mouse on tmux
setw -g mouse on

# escape-time
set-option -sg escape-time 10

# focus-events
set-option -g focus-events on

# term gui colors
set-option -a terminal-features 'xterm-256color:RGB'
set-option -g default-terminal 'tmux-256color'

# sixel support
set -g allow-passthrough on
set -gq allow-passthrough on
set -as terminal-features ';*sixel'
set -ga terminal-overrides ',*Ss=\E[%p1%d q:Se=\E[2 q'

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'

# set leader ^Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# act like vim
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# synchronize input [toggle]
bind-key S setw synchronize-panes

# reload config
unbind r
bind r source-file .tmux.conf

# splitting opens on same path
bind '%' splitw -h -c '#{pane_current_path}'
bind '"' splitw -c '#{pane_current_path}'

# dracula customizations
set -g @dracula-show-left-icon session
set -g @dracula-plugins 'cpu-usage ram-usage time'
# cpu-usage options
set -g @dracula-cpu-usage-colors 'pink white'
set -g @dracula-cpu-display-load true
set -g @dracula-day-month true
# ram-usage options
set -g @dracula-ram-usage-colors 'dark_purple white'
# time options
set -g @dracula-time-colors 'pink white'
set -g @dracula-show-timezone false
set -g @dracula-military-time true
set -g @dracula-time-format '%F %R'
# enable powerline symbols
set -g @dracula-show-powerline true

run '~/.tmux/plugins/tpm/tpm'
